name: build_and_test
on:
  pull_request:
jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Select XCode version
      run: sudo xcode-select -s /Applications/Xcode_15.3.app
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2

    - name: Install Fastlane
      run: gem install fastlane
    
    - name: Run tests
      run: cd CoinGekoiOS/; fastlane tests